### ISSUE TITLE
incorrect doc links

### ISSUE THREAD

**Issue by DarkPatrick** [danielaparker/unicode_traits#1]
Hi.

Almost all links on documentation are invalid.
Like all links on this page:
https://github.com/danielaparker/unicode_traits/blob/master/doc/md/Home.md
They either lack ".md" at the end, or should (probably) redirect to your wiki page
like links here:
https://github.com/danielaparker/unicode_traits/wiki

Best regards.

**Comment by danielaparker** [comment]
Fixed! Thanks for reporting.
